/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Menu;

import DonHang.FormQuanLyDonHang;
import NhaCC.FormNhaCC;
import NhapSanPham.FormNhapSanPham;
import SanPham.FormQLSPham;
import TaiKhoan.FormQLTKhoan;
import ThanhToan.FormThanhToanDonHang;
import ThongKe.FormThongKE;

/**
 *
 * @author Đặng Minh Hằng
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnQLSanPham = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnQLNHACC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnQLTaiKhoan = new javax.swing.JButton();
        btnQuanLyNhap = new javax.swing.JButton();
        btnQuanLyDonHang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Chào mừng đến với shop LinhBEE");

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/logout.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(btnDangXuat)
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnDangXuat))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQLSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/quanao1.png"))); // NOI18N
        btnQLSanPham.setText("Quản lý sản phẩm");
        btnQLSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSanPhamActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 91, 223, 101));

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/thongkeicon.png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, 223, 90));

        btnQLNHACC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/user.png"))); // NOI18N
        btnQLNHACC.setText("Quản lý nhà CC");
        btnQLNHACC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNHACCActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLNHACC, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 205, 223, 86));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/logoShop.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 13, 461, 481));

        btnQLTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/user.png"))); // NOI18N
        btnQLTaiKhoan.setText("Quản lý nhân viên");
        btnQLTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTaiKhoanActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 94, 223, 95));

        btnQuanLyNhap.setText("Quản lý Nhập");
        btnQuanLyNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhapActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuanLyNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 223, 90));

        btnQuanLyDonHang.setText("Quản lý đơn hàng");
        btnQuanLyDonHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyDonHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuanLyDonHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 220, 86));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 501));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        FormDangNhap frmDangNhap=new FormDangNhap();
        frmDangNhap.pack();
        frmDangNhap.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQLSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSanPhamActionPerformed
        FormQLSPham frm=new FormQLSPham();
        frm.pack();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLSanPhamActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        FormThongKE frm=new FormThongKE();
        frm.pack();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLNHACCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNHACCActionPerformed
        FormNhaCC frm=new FormNhaCC();
        frm.setVisible(true);
        frm.pack();
        this.dispose();
    }//GEN-LAST:event_btnQLNHACCActionPerformed

    private void btnQLTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTaiKhoanActionPerformed
        FormQLTKhoan formQLTK=new FormQLTKhoan();
        formQLTK.pack();
        formQLTK.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQLTaiKhoanActionPerformed

    private void btnQuanLyDonHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyDonHangActionPerformed
        FormQuanLyDonHang form=new FormQuanLyDonHang();
        form.pack();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanLyDonHangActionPerformed

    private void btnQuanLyNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhapActionPerformed
        FormNhapSanPham form=new FormNhapSanPham();
        form.pack();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuanLyNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLNHACC;
    private javax.swing.JButton btnQLSanPham;
    private javax.swing.JButton btnQLTaiKhoan;
    private javax.swing.JButton btnQuanLyDonHang;
    private javax.swing.JButton btnQuanLyNhap;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
