/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package TaiKhoan;

import ConnectDB.ConnectionDB;
import Menu.FormMenu;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Đặng Minh Hằng
 */
public class FormQLTKhoan extends javax.swing.JFrame {
    ConnectionDB conned=new ConnectionDB();
    DefaultTableModel dtable=null;
    TaiKhoanObject taiKhoanChon=null;
    /**
     * Creates new form FormQLTKhoan
     */
    public FormQLTKhoan() {
        initComponents();
        dtable=(DefaultTableModel) tblTaiKhoan.getModel();
        dtable.addColumn("Mã");
        dtable.addColumn("Tên");
        dtable.addColumn("Mật khẩu");
        dtable.addColumn("Họ Tên");
        dtable.addColumn("SĐt");
        dtable.addColumn("Địa chỉ");
        dtable.addColumn("Ngày sinh");
        dtable.addColumn("Quyền");
        loadBang();
        
    }
    private void loadBang(){
        ArrayList<TaiKhoanObject>dsTaiKhoan=conned.dsTK();
        for(int i=tblTaiKhoan.getRowCount()-1;i>=0; i--){
            dtable.removeRow(i);
        }
        for(TaiKhoanObject tk :dsTaiKhoan){
            Vector<Object> vec=new Vector<>();
            vec.add(tk.getMaTK());
            vec.add(tk.getTenDN());
            vec.add(tk.getMatKhau());
            vec.add(tk.getHoTen());
            vec.add(tk.getSoDT());
            vec.add(tk.getDiaChi());
            vec.add(tk.getNgaySinh());
            vec.add(tk.getQuyen());
            dtable.addRow(vec);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenDN = new javax.swing.JTextField();
        txtMK = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtMaTK = new javax.swing.JTextField();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaiKhoan = new javax.swing.JTable();
        btnNhapMoi = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cboQuyen = new javax.swing.JComboBox<String>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Mã tài khoản");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 27, -1, -1));

        jLabel3.setText("Tên đăng nhập");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel4.setText("Họ tên");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 160, -1, -1));

        jLabel5.setText("Mật khẩu");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 118, -1, -1));

        jLabel6.setText("Ngày sinh");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel7.setText("Số ĐT");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 64, -1, -1));

        jLabel8.setText("Địa chỉ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 115, -1, -1));
        jPanel2.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 152, 149, -1));
        jPanel2.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 64, 149, -1));
        jPanel2.add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 64, 149, -1));

        txtMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMKActionPerformed(evt);
            }
        });
        jPanel2.add(txtMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 112, 149, -1));

        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });
        jPanel2.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 112, 149, -1));

        txtMaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTKActionPerformed(evt);
            }
        });
        jPanel2.add(txtMaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 24, 149, -1));

        dateNgaySinh.setDateFormatString("dd/MM/yyyy");
        jPanel2.add(dateNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 149, -1));

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/refresh-page-option.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 140, -1));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/cross-remove-sign.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 140, 40));

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/them.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 140, -1));

        tblTaiKhoan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTaiKhoan.setRowHeight(20);
        tblTaiKhoan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTaiKhoan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 260, 810, 260));

        btnNhapMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TaiKhoan/delete.png"))); // NOI18N
        btnNhapMoi.setText("Nhập mới");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhapMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, 140, -1));

        jLabel10.setText("Quyền");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        cboQuyen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Nhân viên" }));
        jPanel2.add(cboQuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 150, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 76, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý tài khoản");

        txtTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTimKiemMouseClicked(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/magnifier-tool (1).png"))); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/reply.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnQuayLai)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnQuayLai)
                        .addComponent(jLabel1)))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 812, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMKActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtMaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTKActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        FormMenu frmMenu=new FormMenu();
        frmMenu.setVisible(true);
        frmMenu.pack();
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void tblTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaiKhoanMouseClicked
        int dongChon=tblTaiKhoan.getSelectedRow();
        if(dongChon!=-1){
            String maTK=tblTaiKhoan.getValueAt(dongChon, 0).toString();
            String tenDN=tblTaiKhoan.getValueAt(dongChon, 1).toString();
            String matKhau=tblTaiKhoan.getValueAt(dongChon, 2).toString();
            String hoTen=tblTaiKhoan.getValueAt(dongChon, 3).toString();
            String sdt=tblTaiKhoan.getValueAt(dongChon, 4).toString();
            String diaChi=tblTaiKhoan.getValueAt(dongChon, 5).toString();
            Date ngaySinh= (Date) tblTaiKhoan.getValueAt(dongChon, 6);
            String quyen=tblTaiKhoan.getValueAt(dongChon, 7).toString();
            taiKhoanChon=new TaiKhoanObject(maTK, tenDN, matKhau, hoTen, sdt, diaChi, ngaySinh,quyen);
            txtMaTK.setText(maTK);
            txtTenDN.setText(tenDN);
            txtMK.setText(matKhau);
            txtHoTen.setText(hoTen);
            txtSDT.setText(sdt);
            txtDiaChi.setText(diaChi);
            dateNgaySinh.setDate(ngaySinh);
            cboQuyen.setSelectedItem(quyen+"");
        }
    }//GEN-LAST:event_tblTaiKhoanMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String maTK=txtMaTK.getText();
        if (maTK.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mã tài khoản không để trống");
            return;
        }
        String tenDN=txtTenDN.getText();
        if (tenDN.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập không để trống");
            return;
        }
        String matKhau=txtMK.getText();
        if (matKhau.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Mật khẩu không để trống");
            return;
        }
        String hoTen=txtHoTen.getText();
        if (hoTen.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Họ tên không để trống");
            return;
        }
        String sdt=txtSDT.getText();
        String diaChi=txtDiaChi.getText();
        java.util.Date ns=dateNgaySinh.getDate();
        String ngaySinh=sdf.format(ns)+"";
        if(conned.themTaiKhoan(maTK, tenDN, matKhau, hoTen,  sdt, diaChi, ngaySinh)){
            JOptionPane.showMessageDialog(null, "Thêm tài khoản thành công !");
            loadBang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Thêm tài khoản thất bại !");
            return;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        
        txtMaTK.setText("");
        txtTenDN.setText("");
        txtMK.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtDiaChi.setText("");
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int cf=JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xoá mã "+taiKhoanChon.getMaTK()+"?",
                "Xác nhận xoá", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(cf==JOptionPane.OK_OPTION){
            if(conned.xoaTaiKhoan(taiKhoanChon.getMaTK())){
            JOptionPane.showMessageDialog(null, "Xoá tài khoản thành công !");
            loadBang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Xoá tài khoản thất bại !");
            return;
        }
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String maTK=txtMaTK.getText();
        String tenDN=txtTenDN.getText();
        String matKhau=txtMK.getText();
        String hoTen=txtHoTen.getText();
        String sdt=txtSDT.getText();
        String diaChi=txtDiaChi.getText();
        java.util.Date ns=dateNgaySinh.getDate();
        String ngaySinh=sdf.format(ns)+"";
        if(conned.updateTaiKhoan(maTK, tenDN, matKhau, hoTen, sdt, diaChi, ngaySinh)){
            JOptionPane.showMessageDialog(null, "Sửa tài khoản thành công !");
            loadBang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Sửa tài khoản thất bại !");
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimKiemMouseClicked
        loadBang();
    }//GEN-LAST:event_txtTimKiemMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ArrayList<TaiKhoanObject>dsTaiKhoan=conned.dsTK();
        for(int i=tblTaiKhoan.getRowCount()-1;i>=0; i--){
            dtable.removeRow(i);
        }
        String timKiem=txtTimKiem.getText();
        for(TaiKhoanObject tk :dsTaiKhoan){
            if(tk.getTenDN().contains(timKiem)||tk.getHoTen().contains(timKiem)){
                Vector<Object> vec=new Vector<>();
            vec.add(tk.getMaTK());
            vec.add(tk.getTenDN());
            vec.add(tk.getMatKhau());
            vec.add(tk.getHoTen());
            vec.add(tk.getSoDT());
            vec.add(tk.getDiaChi());
            vec.add(tk.getNgaySinh());
            dtable.addRow(vec);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQLTKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQLTKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQLTKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQLTKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQLTKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboQuyen;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTaiKhoan;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMaTK;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
