/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ThanhToan;

import ConnectDB.ConnectionDB;
import GiaoDienCuaNhanVien.MenuNV;
import Menu.FormMenu;
import SanPham.SanPhamObject;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Đặng Minh Hằng
 */
public class FormThanhToanDonHang extends javax.swing.JFrame {
    
    DefaultTableModel dtm=null;
    SanPhamObject sanPhamChon=null;
    ConnectionDB connected=new ConnectionDB();
    /**
     * Creates new form FormThanhToanDonHang
     */
    public FormThanhToanDonHang() {
        initComponents();
        dtm=(DefaultTableModel) tblPhieuXuat.getModel();
        loadBang();
        loadCombo();
    }
    private void loadCombo(){
        ConnectionDB conn=new ConnectionDB();
        cboPhieuXuat.removeAllItems();
        for(ThanhToanObject tt:conn.dsThanhToan()){
            cboPhieuXuat.addItem(tt);
        }
        cboSanPham.removeAllItems();
        for(SanPhamObject sp:conn.dsSanPham()){
            cboSanPham.addItem(sp);
        }
    }
    private void loadBang(){
        for(int i=tblPhieuXuat.getRowCount()-1; i>=0; i--){
            dtm.removeRow(i);
        }
        ConnectionDB cnn=new ConnectionDB();
        for(PhieuXuatObjet p :cnn.dsPhieuXuat()){
            Vector<Object>vec=new Vector<>();
            vec.add(p.getMaPhieu());
            vec.add(p.getNgay());
            vec.add(p.getTenKH());
            vec.add(p.getMaSP());
            vec.add(p.getSl());
            vec.add(p.getDonGia());
            dtm.addRow(vec);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQuayLai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPhieuXuat = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaPhieu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dateNgayX = new com.toedter.calendar.JDateChooser();
        btnTaoPhieu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cboPhieuXuat = new javax.swing.JComboBox<ThanhToanObject>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuongXuat = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDonGiaXuat = new javax.swing.JTextField();
        btnXuatHang = new javax.swing.JButton();
        btnXoaPhieu = new javax.swing.JButton();
        cboSanPham = new javax.swing.JComboBox<SanPhamObject>();
        jLabel11 = new javax.swing.JLabel();
        txtSLCon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/reply.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Thanh toán đơn hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuayLai)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuayLai))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        tblPhieuXuat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblPhieuXuat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu", "Ngày", "Tên khách hàng", "Mã sản phẩm", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tblPhieuXuat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 1040, 193));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Mã phiếu xuất:");

        jLabel4.setText("Ngày xuất:");

        jLabel5.setText("Tên khách hàng");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/cross-remove-sign.png"))); // NOI18N
        jButton1.setText("Reset");

        btnTaoPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/them.png"))); // NOI18N
        btnTaoPhieu.setText("Tạo phiếu");
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addComponent(dateNgayX, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTenKH)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTaoPhieu)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dateNgayX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTaoPhieu, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 380, 240));

        jLabel2.setText("Phiếu xuât");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Phiếu xuất:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel2.add(cboPhieuXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 283, -1));

        jLabel8.setText("Sản phẩm:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel9.setText("Số lượng xuất:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel2.add(txtSoLuongXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 280, -1));

        jLabel10.setText("Đơn giá xuất:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel2.add(txtDonGiaXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 280, -1));

        btnXuatHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ThanhToan/thanhtoan.png"))); // NOI18N
        btnXuatHang.setText("Xuất hàng");
        btnXuatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnXuatHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        btnXoaPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/cross-remove-sign.png"))); // NOI18N
        btnXoaPhieu.setText("Xoá phiếu");
        btnXoaPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhieuActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 160, 60));

        cboSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSanPhamActionPerformed(evt);
            }
        });
        jPanel2.add(cboSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 284, -1));

        jLabel11.setText("Số lượng còn:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtSLCon.setEnabled(false);
        jPanel2.add(txtSLCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 280, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 570, 240));

        jLabel6.setText("Chi tiết phiếu xuất");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        MenuNV frmMenu=new MenuNV();
        frmMenu.setVisible(true);
        frmMenu.pack();
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd");
        String ma=txtMaPhieu.getText();
        String ngayX=sdf.format(dateNgayX.getDate());
        String tenKH=txtTenKH.getText();
        ConnectionDB cnn=new ConnectionDB();
        if(cnn.themPhieuXuat(ma, ngayX, tenKH)){
            JOptionPane.showMessageDialog(null, "Tạo phiếu xuất thành công!!");
            loadCombo();
        }
        else{
            JOptionPane.showMessageDialog(null, "Tạo phiếu xuất thất bại");
            return;
        }
    }//GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnXoaPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhieuActionPerformed
        ThanhToanObject tt=(ThanhToanObject) cboPhieuXuat.getSelectedItem();
        if(tt!=null){
            ConnectionDB cnn=new ConnectionDB();
            String ma=tt.getMaPhieu();
            int cf=JOptionPane.showConfirmDialog(null, "Bạn coá chắc xoá phiếu không?", "Xác nhận xoá", JOptionPane.YES_NO_OPTION);
            if(cf==JOptionPane.YES_OPTION){
                if(cnn.xoaPhieuXuat(ma)){
                    JOptionPane.showMessageDialog(null, "Xoá thành công !");
                    loadCombo();
                    loadBang();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Xoá thất bại !");
                    return;
                }
                
            }
            else{
                
                return;
            }
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnXoaPhieuActionPerformed

    private void btnXuatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHangActionPerformed
        SanPhamObject sp=(SanPhamObject) cboSanPham.getSelectedItem();
        ThanhToanObject tt=(ThanhToanObject) cboPhieuXuat.getSelectedItem();
        int slX=Integer.parseInt(txtSoLuongXuat.getText());
        float donGia=Float.parseFloat(txtDonGiaXuat.getText());
        double thanhTien=slX*donGia;
        ConnectionDB cnn=new ConnectionDB();
        if(cnn.themChiTietPhieuXuat(tt.getMaPhieu(), sp.getMaSP(), slX, donGia,thanhTien)){
            JOptionPane.showMessageDialog(null, "Xuất hàng thành công");
            loadBang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Xuất hàng thất bại");
            return;
        }
    }//GEN-LAST:event_btnXuatHangActionPerformed

    private void cboSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSanPhamActionPerformed
        SanPhamObject sp=(SanPhamObject) cboSanPham.getSelectedItem();
        if(sp!=null){
            txtSLCon.setText(sp.getSoLuong()+"");
        }
        else{
            return;
        }
    }//GEN-LAST:event_cboSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThanhToanDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThanhToanDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThanhToanDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThanhToanDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThanhToanDonHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JButton btnXoaPhieu;
    private javax.swing.JButton btnXuatHang;
    private javax.swing.JComboBox<ThanhToanObject> cboPhieuXuat;
    private javax.swing.JComboBox<SanPhamObject> cboSanPham;
    private com.toedter.calendar.JDateChooser dateNgayX;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPhieuXuat;
    private javax.swing.JTextField txtDonGiaXuat;
    private javax.swing.JTextField txtMaPhieu;
    private javax.swing.JTextField txtSLCon;
    private javax.swing.JTextField txtSoLuongXuat;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
