/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TonKho;

import ConnectDB.ConnectionDB;
import GiaoDienCuaNhanVien.MenuNV;
import SanPham.SanPhamObject;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giang Phan
 */
public class FormTonKho extends javax.swing.JFrame {
    DefaultTableModel dtm=null;
    TonKhoObject tonKhoChon=null;
    /**
     * Creates new form FormTonKho
     */
    public FormTonKho() {
        initComponents();
        dtm=(DefaultTableModel) tblTonKho.getModel();
        loadCombo();
        loadBang();
    }
    private void loadCombo(){
        cboSanPham.removeAllItems();
        ConnectionDB cnn=new ConnectionDB();
        for(SanPhamObject sp:cnn.dsSanPham()){
            cboSanPham.addItem(sp);
        }
    }
    private void loadBang(){
        ConnectionDB cnn=new ConnectionDB();
        for(int i=tblTonKho.getRowCount()-1; i>=0; i--){
            dtm.removeRow(i);
        }
        for(TonKhoObject tk:cnn.dsTonKho()){
            Vector<Object>vec=new Vector<>();
            vec.add(tk.getMa());
            vec.add(tk.getMaSP());
            vec.add(tk.getSlNhap());
            vec.add(tk.getSlXuat());
            dtm.addRow(vec);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cboSanPham = new javax.swing.JComboBox<SanPhamObject>();
        btnKiemTra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTonKho = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnQuayLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Sản phẩm:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        getContentPane().add(cboSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, -1));

        btnKiemTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/magnifier-tool (1).png"))); // NOI18N
        btnKiemTra.setText("Kiểm tra");
        btnKiemTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKiemTraActionPerformed(evt);
            }
        });
        getContentPane().add(btnKiemTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        tblTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tồn", "Mã sản phẩm", "Số lượng nhập", "Số lượng xuất"
            }
        ));
        tblTonKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTonKhoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTonKho);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 870, 230));

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/cross-remove-sign.png"))); // NOI18N
        btnXoa.setText("Xoá tồn kho");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        btnQuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SanPham/reply.png"))); // NOI18N
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Tồn kho");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(btnQuayLai)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(btnQuayLai))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKiemTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKiemTraActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("ddMMyyyy");
        String ma=sdf.format(Date.from(Instant.now()));
        SanPhamObject sp=(SanPhamObject) cboSanPham.getSelectedItem();
        ConnectionDB cnn=new ConnectionDB();
        if(cnn.themTonKho(ma, sp.getMaSP(), cnn.slNhap(sp.getMaSP()), cnn.slXUAT(sp.getMaSP()))){
            JOptionPane.showMessageDialog(null, "Cập nhật thành công !");
            loadBang();
        }
        else{
            JOptionPane.showMessageDialog(null, "Cập nhật thất bại !");
            return;
        }
    }//GEN-LAST:event_btnKiemTraActionPerformed

    private void tblTonKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTonKhoMouseClicked
        int row=tblTonKho.getSelectedRow();
        if(row!=-1){
            tonKhoChon=new TonKhoObject(tblTonKho.getValueAt(row, 0).toString(),
                    tblTonKho.getValueAt(row, 1).toString(),
                    Integer.parseInt(tblTonKho.getValueAt(row, 2).toString()),
                    Integer.parseInt(tblTonKho.getValueAt(row, 3).toString()));
        }
    }//GEN-LAST:event_tblTonKhoMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(tonKhoChon!=null){
            ConnectionDB cnn=new ConnectionDB();
            if(cnn.xoaTonKho(tonKhoChon.getMa())){
                loadBang();
            }
            else{
                return;
            }
        }
        else{
            return;
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        MenuNV frm=new MenuNV();
        frm.pack();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTonKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTonKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTonKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTonKho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTonKho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKiemTra;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<SanPhamObject> cboSanPham;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTonKho;
    // End of variables declaration//GEN-END:variables
}
